import type { MenuCategory, ShishaData } from "./menuData"

/** @deprecated Use trpc.menu.getMenu({ tab: "food" }) instead. Kept for legacy pages still migrating. */
export const alacarteData: MenuCategory[] = [
  {
    id: 'breakfast',
    title_az: 'SƏHƏR YEMƏYİ',
    title_ru: 'ЗАВТРАК',
    title_en: 'BREAKFAST',
    title_tr: 'Kahvaltı',
    sortOrder: 10,
    items: [
      { name_az: 'Tavada yumurta', name_ru: 'Яичница', name_en: 'Fried eggs', name_tr: 'Kızarmış yumurta', price: '8 AZN' },
      { name_az: 'Pomidor-yumurta', name_ru: 'Яичница с помидорами', name_en: 'Eggs with tomato', name_tr: 'Domatesli yumurta', price: '10 AZN' },
      { name_az: 'Kükü', name_ru: 'Кюку', name_en: 'Kuku', name_tr: 'Kuku', price: '10 AZN', desc_az: 'Yumurta, göyərti, kərə yağı, qatıq', desc_ru: 'Яйцо, зелень, сливочное масло, йогурт', desc_en: 'Egg, herbs, butter, yogurt', desc_tr: 'Yumurta, otlar, tereyağı, yoğurt' },
      { name_az: 'Pankelər, karamelizə banan, duzlu karamel dondurma', name_ru: 'Панкейки с карамелизированным бананом', name_en: 'Pancakes, caramelized banana, salted caramel ice cream', name_tr: 'Karamelize muzlu pankek, tuzlu karamel dondurma', price: '10 AZN' },
      { name_az: 'İspanaqlı brunch omleti', name_ru: 'Омлет со шпинатом', name_en: 'Brunch omelette with spinach', name_tr: 'Ispanaklı brunch omleti',
      price: '10 AZN', desc_az: 'Pendir, baguette, konfi pomidor', desc_ru: 'Сыр, багет, конфи из помидоров', desc_en: 'Cheese, baguette, confit tomato', desc_tr: 'Peynir, baget, konfi domates' },
      { name_az: 'Yoğurt bowl', name_ru: 'Йогурт боул', name_en: 'Yogurt bowl', name_tr: 'Yoğurt kasesi',
      price: '15 AZN', desc_az: 'Xama, sadə yoğurt, banan, granola, çiyələk', desc_ru: 'Сметана, йогурт, банан, гранола, клубника', desc_en: 'Sour cream, yogurt, banana, granola, strawberry', desc_tr: 'Krema, yoğurt, muz, granola, çilek' },
      { name_az: 'Ənənəvi şəhər yeməyi seti', name_ru: 'Традиционный завтрак сет', name_en: 'Traditional breakfast set', name_tr: 'Geleneksel kahvaltı seti',
      price: '18 AZN', desc_az: 'Mürəbbə, pendir dipi, zeytun, lavaş, yerli pendirlər', desc_ru: 'Варенье, сырный дип, оливки, лаваш, местные сыры', desc_en: 'Jam, cheese dip, olives, lavash, local cheeses', desc_tr: 'Reçel, peynir sosu, zeytin, lavaş, yerli peynirler' },
      { name_az: 'İngilis şəhər yeməyi', name_ru: 'Английский завтрак', name_en: 'English breakfast', name_tr: 'İngiliz kahvaltısı',
      price: '18 AZN', desc_az: 'Göbələk, yumurta, kərə yağı, sosis', desc_ru: 'Грибы, яйцо, сливочное масло, сосиски', desc_en: 'Mushrooms, egg, butter, sausages', desc_tr: 'Mantar, yumurta, tereyağı, sosisler' },
      { name_az: 'Kəsmikli pankeklər', name_ru: 'Сырники', name_en: 'Curd pancakes', name_tr: 'Lor peynirli pankek',
      price: '14 AZN', desc_az: 'Pankek, kəsmik, giləmeyvə', desc_ru: 'Панкейки, творог, ягоды', desc_en: 'Pancakes, curd, berries', desc_tr: 'Pankek, lor peyniri, orman meyveleri' },
      { name_az: 'Giləmeyvə mürəbbəsi ilə fransız tostu', name_ru: 'Французский тост с ягодным вареньем', name_en: 'French toast with berry jam', name_tr: 'Meyve reçelli Fransız tostu',
      price: '14 AZN', desc_az: 'Tost çörəyi, yumurta, süd, giləmeyvə mürəbbəsi', desc_ru: 'Тостовый хлеб, яйцо, молоко, ягодное варенье', desc_en: 'Toast bread, egg, milk, berry jam', desc_tr: 'Tost ekmeği, yumurta, süt, meyve reçeli' },
      { name_az: 'Marinad edilmiş qızılbalıq Benedikt', name_ru: 'Бенедикт с маринованным лососем', name_en: 'Benedict with marinated salmon', name_tr: 'Marine somonlu Benedict',
      price: '27 AZN', desc_az: 'Marinad edilmiş qızılbalıq, poached egg, hollandaise sous', desc_ru: 'Маринованный лосось, яйцо пашот, соус голландез', desc_en: 'Marinated salmon, poached egg, hollandaise sauce', desc_tr: 'Marine somon, poşe yumurta, hollandaise sos' },
      { name_az: 'Xurcun şəhər ləzzətləri', name_ru: 'Завтрак Xurcun', name_en: 'Xurcun breakfast', name_tr: 'Xurcun kahvaltısı',
      price: '18 AZN', desc_az: 'Su samlı simit, kartof samosası, spring roll, qril sucuk', desc_ru: 'Бублик с кунжутом, картофельные самосы, спринг-ролл, гриль-суджук', desc_en: 'Sesame bagel, potato samosas, spring roll, grilled sucuk', desc_tr: 'Susamlı simit, patates samosa, spring roll, ızgara sucuk' },
    ],
  },
  {
    id: 'soups',
    title_az: 'ŞORBALAR',
    title_ru: 'СУПЫ',
    title_en: 'SOUPS',
    title_tr: 'Çorbalar',
    sortOrder: 20,
    items: [
      { name_az: 'Dovğa', name_ru: 'Довга', name_en: 'Dovga', name_tr: 'Dovğa',
      price: '7 AZN', desc_az: 'Sadə qatıq, quru nanə, təzə nanə, zəfəran, zeytun yağı', desc_ru: 'Йогурт, сухая мята, свежая мята, шафран, оливковое масло', desc_en: 'Yogurt, dried mint, fresh mint, saffron, olive oil', desc_tr: 'Yoğurt, kuru nane, taze nane, safran, zeytinyağı' },
      { name_az: 'Qaymaqlı pomidor şorbası', name_ru: 'Томатный крем-суп', name_en: 'Creamy tomato soup', name_tr: 'Kremalı domates çorbası',
      price: '8 AZN', desc_az: 'Pomidor, soğan, kəklikotu, qaymaq', desc_ru: 'Помидоры, лук, чабрец, сливки', desc_en: 'Tomato, onion, thyme, cream', desc_tr: 'Domates, soğan, kekik, krema' },
      { name_az: 'Bakü əriştə şorbası', name_ru: 'Бакинский суп с лапшой', name_en: 'Baku noodle soup', name_tr: 'Bakü erişte çorbası',
      price: '10 AZN', desc_az: 'Xəmir, quzu əti, lobya, quzu bulyonu', desc_ru: 'Тесто, баранина, фасоль, бараний бульон', desc_en: 'Dough, lamb, beans, lamb broth', desc_tr: 'Hamur, kuzu eti, fasulye, kuzu suyu' },
      { name_az: 'Düşbərə şorbası', name_ru: 'Дюшбара', name_en: 'Dushbara soup', name_tr: 'Düşbara çorbası',
      price: '10 AZN', desc_az: 'Xırda düşbərə, quzu əti, bulyon, sirkə', desc_ru: 'Мелкие дюшбары, баранина, бульон, уксус', desc_en: 'Small dumplings, lamb, broth, vinegar', desc_tr: 'Küçük hamur parçaları, kuzu eti, et suyu, sirke' },
    ],
  },
  {
    id: 'salads',
    title_az: 'SALATLAR',
    title_ru: 'САЛАТЫ',
    title_en: 'SALADS',
    title_tr: 'Salatalar',
    sortOrder: 40,
    items: [
      { name_az: 'Tərəvəzli yay salatı', name_ru: 'Овощной салат', name_en: 'Summer vegetable salad', name_tr: 'Yaz sebze salatası',
      price: '10 AZN', desc_az: 'Balqabaq, pomidor, xiyar, avokado, qırmızı soğan, zeytun, turp', desc_ru: 'Тыква, помидоры, огурцы, авокадо, красный лук, оливки, редис', desc_en: 'Pumpkin, tomato, cucumber, avocado, red onion, olives, radish', desc_tr: 'Balkabağı, domates, salatalık, avokado, kırmızı soğan, zeytin, turp' },
      { name_az: 'Rukkola və balqabaq salatı', name_ru: 'Салат с рукколой и тыквой', name_en: 'Arugula and pumpkin salad', name_tr: 'Rukola ve balkabağı salatası',
      price: '15 AZN', desc_az: 'Rukkola, konfi balqabaq, mövsümi tərəvəzlər', desc_ru: 'Руккола, конфи из тыквы, сезонные овощи', desc_en: 'Arugula, confit pumpkin, seasonal vegetables', desc_tr: 'Rukola, konfi balkabağı, mevsim sebzeleri' },
      { name_az: '"Healthy" salat', name_ru: '"Healthy" салат', name_en: '"Healthy" salad', name_tr: '"Healthy" salata',
      price: '15 AZN', desc_az: 'Avokado, əzilmiş qırmızı kələm, alma, qarışıq kahı, blue cheese, çuğundur marmeladı', desc_ru: 'Авокадо, красная капуста, яблоко, салат, сыр с плесенью, мармелад из свеклы', desc_en: 'Avocado, red cabbage, apple, mixed lettuce, blue cheese, beetroot marmalade', desc_tr: 'Avokado, kırmızı lahana, elma, karışık marul, blue cheese, pancar marmeladı' },
      { name_az: 'Qril toyuq Sezar salatı', name_ru: 'Цезарь с курицей гриль', name_en: 'Grilled chicken Caesar salad', name_tr: 'Izgara tavuk Sezar salata',
      price: '21 AZN', desc_az: 'Avokado, yavaş bişmiş toyuq, kahı, ev üsulu mayon sousu', desc_ru: 'Авокадо, курица гриль, салат, домашний майонез', desc_en: 'Avocado, slow-cooked chicken, lettuce, house mayonnaise', desc_tr: 'Avokado, yavaş pişmiş tavuk, marul, ev yapımı mayonez' },
      { name_az: 'Burrata və hisə verilmiş çuğundur', name_ru: 'Буррата с копченой свеклой', name_en: 'Burrata with smoked beetroot', name_tr: 'Burrata ve tütsülenmiş pancar',
      price: '20 AZN', desc_az: 'Burrata, hisə verilmiş çuğundur, nar, sarımsaqlı yoğurt sousu', desc_ru: 'Буррата, копченая свекла, гранат, йогуртовый соус с чесноком', desc_en: 'Burrata, smoked beetroot, pomegranate, garlic yogurt sauce', desc_tr: 'Burrata, tütsülenmiş pancar, nar, sarımsaklı yoğurt sosu' },
      { name_az: 'Yay ləzzətli krevet salatı', name_ru: 'Летний салат с креветками', name_en: 'Summer prawn salad', name_tr: 'Yaz karides salatası',
      price: '24 AZN', desc_az: 'Rukkola, avokado, brokoli, keşniş, portağal, zirə pomidoru, sərt pendir, qaragilə', desc_ru: 'Руккола, авокадо, брокколи, кинза, апельсин, помидоры, твердый сыр, черника', desc_en: 'Arugula, avocado, broccoli, coriander, orange, tomatoes, hard cheese, blueberry', desc_tr: 'Rukola, avokado, brokoli, kişniş, portakal, domates, sert peynir, yaban mersini' },
    ],
  },
  {
    id: 'starters',
    title_az: 'BAŞLANĞICLAR',
    title_ru: 'ЗАКУСКИ',
    title_en: 'APPETIZERS',
    title_tr: 'Başlangıçlar',
    sortOrder: 30,
    items: [
      { name_az: 'Yerli pendir çeşidləri', name_ru: 'Ассорти местных сыров', name_en: 'Local cheese selection', name_tr: 'Yerli peynir seçimi',
      price: '8 AZN', desc_az: 'Yerli pendir çeşidləri, göyərti, zeytun yağı', desc_ru: 'Местные сыры, зелень, оливковое масло', desc_en: 'Local cheeses, herbs, olive oil', desc_tr: 'Yerli peynirler, otlar, zeytinyağı' },
      { name_az: 'Xarici pendir çeşidləri', name_ru: 'Ассорти импортных сыров', name_en: 'Imported cheese selection', name_tr: 'İthal peynir seçimi',
      price: '15 AZN', desc_az: 'Xarici pendir çeşidləri, göyərti, zeytun yağı', desc_ru: 'Импортные сыры, зелень, оливковое масло', desc_en: 'Imported cheeses, herbs, olive oil', desc_tr: 'İthal peynirler, otlar, zeytinyağı' },
      { name_az: 'Turşu çeşidləri', name_ru: 'Ассорти солений', name_en: 'Pickle selection', name_tr: 'Turşu seçimi',
      price: '11 AZN', desc_az: 'Mövsümi turşu tərəvəzləri', desc_ru: 'Сезонные соленые овощи', desc_en: 'Seasonal pickled vegetables', desc_tr: 'Mevsimsel turşu sebzeleri' },
      { name_az: 'Quzu ətindən qutab (3 ədəd)', name_ru: 'Кутаб с бараниной (3 шт)', name_en: 'Lamb qutab (3 pcs)', name_tr: 'Kuzu etli kutab (3 adet)', price: '10 AZN', desc_az: 'Quzu əti ilə hazırlanmış Corat qutabı', desc_ru: 'Кутаб с бараниной по-чоратски', desc_en: 'Corat-style qutab with lamb', desc_tr: 'Kuzu etli Corat kutabı' },
      { name_az: 'Mini quzu qutabı (10 ədəd)', name_ru: 'Мини кутаб с бараниной (10 шт)', name_en: 'Mini lamb qutab (10 pcs)', name_tr: 'Mini kuzu kutabı (10 adet)',
      price: '11 AZN', desc_az: 'Quzu əti ilə mini qutablar', desc_ru: 'Мини кутаб с бараниной', desc_en: 'Mini qutab with lamb', desc_tr: 'Kuzu etli mini kutab' },
      { name_az: 'Teriyaki balıq topları', name_ru: 'Рыбные шарики терияки', name_en: 'Teriyaki fish balls', name_tr: 'Teriyaki balık topları', price: '22 AZN' },
      { name_az: 'Portağal veluté-də tempura krevetləri', name_ru: 'Креветки темпура в апельсиновом велуте', name_en: 'Tempura prawns in orange velouté', name_tr: 'Portakal velouté soslu tempura karides', price: '22 AZN' },
      { name_az: 'Qızardılmış dəniz məhsulları', name_ru: 'Жареные морепродукты', name_en: 'Fried seafood', name_tr: 'Kızartılmış deniz ürünleri',
      price: '22 AZN', desc_az: 'Xırtıldayan kalmar, krevetlər, limon-mayo sousu', desc_ru: 'Хрустящий кальмар, креветки, лимонный майонез', desc_en: 'Crispy calamari, prawns, lemon-mayo sauce', desc_tr: 'Çıtır kalamar, karides, limonlu mayonez sosu' },
      { name_az: 'Laym ilə marinadlanmış toyuq filesi', name_ru: 'Куриное филе в маринаде из лайма', name_en: 'Lime marinated chicken fillet', name_tr: 'Lime ile marine edilmiş tavuk fileto',
      price: '14 AZN', desc_az: 'Mövsümi tərəvəzlər, laym-balı sous, portağal', desc_ru: 'Сезонные овощи, лаймовый медовый соус, апельсин', desc_en: 'Seasonal vegetables, lime-honey sauce, orange', desc_tr: 'Mevsim sebzeleri, lime-bal sosu, portakal' },
      { name_az: 'Yerli məzə boşqabı', name_ru: 'Тарелка местных мезе', name_en: 'Local meze platter', name_tr: 'Yerli meze tabağı',
      price: '16 AZN', desc_az: 'Yer məzələrindən seçmə boşqab', desc_ru: 'Ассорти местных мезе', desc_en: 'Selection of local mezes', desc_tr: 'Yerli mezelerden seçki' },
      { name_az: 'Toyuqlu tərəvəz bükməsi', name_ru: 'Спринг-роллы с курицей', name_en: 'Chicken vegetable spring rolls', name_tr: 'Tavuklu sebzeli spring roll',
      price: '18 AZN', desc_az: 'Toyuq, tərəvəz, spring roll xəmiri', desc_ru: 'Курица, овощи, рисовая бумага', desc_en: 'Chicken, vegetables, spring roll wrapper', desc_tr: 'Tavuk, sebzeler, spring roll hamuru' },
    ],
  },
  {
    id: 'main_courses',
    title_az: 'ƏSAS YEMƏKLƏR',
    title_ru: 'ОСНОВНЫЕ БЛЮДА',
    title_en: 'MAIN COURSES',
    title_tr: 'Ana Yemekler',
    sortOrder: 60,
    items: [
      { name_az: 'Üzüm yarpağından dolma', name_ru: 'Долма в виноградных листьях', name_en: 'Stuffed grape leaves', name_tr: 'Asma yaprağında dolma',
      price: '16 AZN', desc_az: 'Üzüm yarpağı, düyü, göyərti, ət, qatıq sousu', desc_ru: 'Виноградные листья, рис, зелень, мясо, йогуртовый соус', desc_en: 'Grape leaves, rice, herbs, meat, yogurt sauce', desc_tr: 'Asma yaprağı, pirinç, otlar, et, yoğurt sosu' },
      { name_az: 'Toyuq rulet levengisi', name_ru: 'Куриный рулет', name_en: 'Chicken roll', name_tr: 'Tavuk ruleti',
      price: '20 AZN', desc_az: 'Toyuq ruleti, qoz, şallot, sous', desc_ru: 'Куриный рулет, грецкий орех, лук-шалот, соус', desc_en: 'Chicken roll, walnut, shallot, sauce', desc_tr: 'Tavuk ruleti, ceviz, şalot, sos' },
      { name_az: 'Mal əti burger', name_ru: 'Бургер с говядиной', name_en: 'Beef burger', name_tr: 'Dana eti burger',
      price: '20 AZN', desc_az: 'Mal əti, pendir, kartof fri', desc_ru: 'Говядина, сыр, картофель фри', desc_en: 'Beef, cheese, french fries', desc_tr: 'Dana eti, peynir, patates kızartması' },
      { name_az: 'Mal əti fisincan', name_ru: 'Фисинджан из говядины', name_en: 'Beef fisincan', name_tr: 'Dana eti fisincan',
      price: '21 AZN', desc_az: 'Mal əti, qoz, soğan, yerli ədviyyatlar', desc_ru: 'Говядина, грецкий орех, лук, местные специи', desc_en: 'Beef, walnut, onion, local spices', desc_tr: 'Dana eti, ceviz, soğan, yerli baharatlar' },
      { name_az: 'Quzu qolundan buğlama', name_ru: 'Буглама из бараньей ноги', name_en: 'Lamb shank buglama', name_tr: 'Kuzu incik buğlama',
      price: '25 AZN', desc_az: 'Bişmiş quzu budu, sous, kartof əzməsi', desc_ru: 'Тушеная баранья нога, соус, картофельное пюре', desc_en: 'Braised lamb shank, sauce, mashed potato', desc_tr: 'Pişmiş kuzu incik, sos, patates püresi' },
      { name_az: 'Xüsusi quzu döyməsi', name_ru: 'Особая баранина тушеная', name_en: 'Special lamb stew', name_tr: 'Özel kuzu güveci',
      price: '22 AZN', desc_az: 'Quzu əti, soğan, pomidor, yerli ədviyyatlar', desc_ru: 'Баранина, лук, помидоры, местные специи', desc_en: 'Lamb, onion, tomato, local spices', desc_tr: 'Kuzu eti, soğan, domates, yerli baharatlar' },
      { name_az: 'Kajun ədviyyatlı böyük krevetlər', name_ru: 'Крупные креветки с кайенским перцем', name_en: 'Large cajun prawns', name_tr: 'Kajun baharatlı büyük karidesler',
      price: '28 AZN', desc_az: 'Kajun ədviyyatı ilə hazırlanmış krevetlər', desc_ru: 'Креветки с кайенской приправой', desc_en: 'Prawns with cajun seasoning', desc_tr: 'Kajun baharatlı karidesler' },
      { name_az: 'Qızıl balıq meunière', name_ru: 'Лосось мёньер', name_en: 'Salmon meunière', name_tr: 'Somon meunière',
      price: '38 AZN', desc_az: 'Qızıl balıq, kərə yağı, limon, göyərti', desc_ru: 'Лосось, сливочное масло, лимон, зелень', desc_en: 'Salmon, butter, lemon, herbs', desc_tr: 'Somon, tereyağı, limon, otlar' },
      { name_az: 'Qril sudak balığı', name_ru: 'Судак на гриле', name_en: 'Grilled zander', name_tr: 'Izgara levrek',
      price: '21 AZN', desc_az: 'Quru zoğal, kərə yağı, soğan, sarıkök', desc_ru: 'Сухой барбарис, сливочное масло, лук, куркума', desc_en: 'Dried barberry, butter, onion, turmeric', desc_tr: 'Kuru berberis, tereyağı, soğan, zerdeçal' },
      { name_az: 'Qızıl balıq cravlaksı', name_ru: 'Гравлакс из лосося', name_en: 'Salmon gravlax', name_tr: 'Somon gravlaks',
      price: '24 AZN', desc_az: 'Marinad edilmiş qızıl balıq, göyərti, sous', desc_ru: 'Маринованный лосось, зелень, соус', desc_en: 'Marinated salmon, herbs, sauce', desc_tr: 'Marine somon, otlar, sos' },
      { name_az: 'Quzu ətindən basdırma', name_ru: 'Басдырма из баранины', name_en: 'Lamb basdirma', name_tr: 'Kuzu bastırma', price: '21 AZN', desc_az: 'Quzu əti, quzu jus sousu, kərəviz püresi, buxarda tərəvəzlər', desc_ru: 'Баранина, соус из баранины, пюре из сельдерея, овощи на пару', desc_en: 'Lamb, lamb jus sauce, celery puree, steamed vegetables', desc_tr: 'Kuzu eti, kuzu suyu sosu, kereviz püresi, buharda sebzeler' },
      { name_az: 'File minyon, trüf sousu ilə', name_ru: 'Филе миньон с трюфельным соусом', name_en: 'Filet mignon with truffle sauce', name_tr: 'Trüf soslu file mignon',
      price: '50 AZN', desc_az: 'File minyon, trüf madeyra sousu', desc_ru: 'Филе миньон, трюфельный мадейра соус', desc_en: 'Filet mignon, truffle madeira sauce', desc_tr: 'File mignon, trüf madeira sosu' },
      { name_az: 'Ribay steyk 350 qr', name_ru: 'Рибай стейк 350 г', name_en: 'Ribeye steak 350g', name_tr: 'Ribeye steak 350g',
      price: '80 AZN', desc_az: '350 qr ribay steyk, sous və qarnir ilə', desc_ru: 'Рибай стейк 350 г, соус и гарнир', desc_en: 'Ribeye steak 350g, sauce and garnish', desc_tr: 'Ribeye steak 350g, sos ve garnitür ile' },
      { name_az: 'Laym və qril olunmuş can əti salatı', name_ru: 'Салат с мясом и лаймом', name_en: 'Lime grilled meat salad', name_tr: 'Lime ızgara et salatası',
      price: '22 AZN', desc_az: 'Marinadlı xiyar, pomidor, kahı, susam, cəfəri, kök', desc_ru: 'Маринованные огурцы, помидоры, салат, кунжут, петрушка, морковь', desc_en: 'Marinated cucumber, tomato, lettuce, sesame, parsley, carrot', desc_tr: 'Marine salatalık, domates, marul, susam, maydanoz, havuç' },
    ],
  },
  {
    id: 'sides',
    title_az: 'QARNAİRLƏR',
    title_ru: 'ГАРНИРЫ',
    title_en: 'SIDES',
    title_tr: 'Garnitürler',
    sortOrder: 70,
    items: [
      { name_az: 'Sarımsaq ilə kartof', name_ru: 'Картофель с чесноком', name_en: 'Garlic potatoes', name_tr: 'Sarımsaklı patates', price: '6 AZN' },
      { name_az: 'Kartof fri', name_ru: 'Картофель фри', name_en: 'French fries', name_tr: 'Patates kızartması', price: '6 AZN' },
      { name_az: 'Buxarda bişmiş mövsümi tərəvəzlər', name_ru: 'Овощи на пару', name_en: 'Steamed seasonal vegetables', name_tr: 'Buharda pişmiş mevsim sebzeleri', price: '7 AZN' },
      { name_az: 'Buxarda zəfəranlı düyü', name_ru: 'Рис с шафраном на пару', name_en: 'Steamed saffron rice', name_tr: 'Buharda safranlı pirinç', price: '6 AZN' },
      { name_az: 'Yunan üslubunda zeytinli kartof', name_ru: 'Картофель с оливками по-гречески', name_en: 'Greek style potato with olives', name_tr: 'Zeytinli Yunan usulü patates', price: '9 AZN' },
      { name_az: 'Qril toyuq filesi', name_ru: 'Куриное филе на гриле', name_en: 'Grilled chicken fillet', name_tr: 'Izgara tavuk fileto', price: '10 AZN' },
      { name_az: 'Tempura krevetlər (5 ədəd)', name_ru: 'Креветки темпура (5 шт)', name_en: 'Tempura prawns (5 pcs)', name_tr: 'Tempura karides (5 adet)', price: '15 AZN' },
    ],
  },
  {
    id: 'pasta_risotto',
    title_az: 'PASTA & RİZOTTO',
    title_ru: 'ПАСТА И РИЗОТТО',
    title_en: 'PASTA & RISOTTO',
    title_tr: 'Makarna & Risotto',
    sortOrder: 50,
    items: [
      { name_az: 'Pomidorlu spagetti', name_ru: 'Спагетти с помидорами', name_en: 'Tomato spaghetti', name_tr: 'Domatesli spagetti',
      price: '16 AZN', desc_az: 'Pomidor sousu, sarımsaq, reyhan, parmesan', desc_ru: 'Томатный соус, чеснок, базилик, пармезан', desc_en: 'Tomato sauce, garlic, basil, parmesan', desc_tr: 'Domates sosu, sarımsak, fesleğen, parmesan' },
      { name_az: 'Can əti penne', name_ru: 'Пенне с мясом', name_en: 'Meat penne', name_tr: 'Etli penne',
      price: '18 AZN', desc_az: 'Can əti, qaymaq, sarımsaq, parmesan, quru pomidor, cəfəri, kərəviz', desc_ru: 'Мясо, сливки, чеснок, пармезан, вяленые помидоры, петрушка, сельдерей', desc_en: 'Meat, cream, garlic, parmesan, sun-dried tomato, parsley, celery', desc_tr: 'Et, krema, sarımsak, parmesan, kurutulmuş domates, maydanoz, kereviz' },
      { name_az: 'Sarımsaqlı kərə yağında toyuq Alfredo', name_ru: 'Курица Альфредо со сливочным маслом и чесноком', name_en: 'Chicken Alfredo with garlic butter', name_tr: 'Sarımsaklı tereyağında tavuk Alfredo',
      price: '18 AZN', desc_az: 'Toyuq, qaymaq, sarımsaq, parmesan, göbələk', desc_ru: 'Курица, сливки, чеснок, пармезан, грибы', desc_en: 'Chicken, cream, garlic, parmesan, mushroom', desc_tr: 'Tavuk, krema, sarımsak, parmesan, mantar' },
      { name_az: 'Krevetli risotto', name_ru: 'Ризотто с креветками', name_en: 'Prawn risotto', name_tr: 'Karidesli risotto',
      price: '28 AZN', desc_az: 'Krevet, risotto düyüsü, parmesan, zəfəran yağı', desc_ru: 'Креветки, рис для ризотто, пармезан, шафрановое масло', desc_en: 'Prawn, risotto rice, parmesan, saffron oil', desc_tr: 'Karides, risotto pirinci, parmesan, safran yağı' },
      { name_az: 'Qızıl balıq və ispanıqlı tagliatelle', name_ru: 'Тальятелле с лососем и шпинатом', name_en: 'Salmon and spinach tagliatelle', name_tr: 'Somonlu ve ıspanaklı tagliatelle',
      price: '28 AZN', desc_az: 'Qızıl balıq, sarımsaq, ispanaq, limon qabığı və suyu, qaymaq', desc_ru: 'Лосось, чеснок, шпинат, цедра и сок лимона, сливки', desc_en: 'Salmon, garlic, spinach, lemon zest and juice, cream', desc_tr: 'Somon, sarımsak, ıspanak, limon kabuğu ve suyu, krema' },
    ],
  },
  {
    id: 'desserts',
    title_az: 'ŞİRNİYYATLAR',
    title_ru: 'ДЕСЕРТЫ',
    title_en: 'DESSERTS',
    title_tr: 'Tatlılar',
    sortOrder: 80,
    items: [
      /* FRUIT & NEW NOTES */
      { name_az: 'Çiyələkli tart', name_ru: 'Клубничный тарт', name_en: 'Strawberry tart', name_tr: 'Çilekli tart', price: '14 AZN' },
      { name_az: 'Klassik tiramisu', name_ru: 'Классический тирамису', name_en: 'Classic tiramisu', name_tr: 'Klasik tiramisu', price: '16 AZN' },
      { name_az: 'Şokoladlı vulkan (dondurma ilə)', name_ru: 'Шоколадный вулкан (с мороженым)', name_en: 'Chocolate volcano (with ice cream)', name_tr: 'Çikolatalı volkan (dondurmalı)', price: '16 AZN' },
      { name_az: 'Mangolu muss', name_ru: 'Манговый мусс', name_en: 'Mango mousse', name_tr: 'Mangolu mus', price: '12 AZN', is_gluten_free: true },
      /* CHOCOLATE & CLASSIC DELIGHTS */
      { name_az: 'Kokoslu keyk', name_ru: 'Кокосовый кекс', name_en: 'Coconut cake', name_tr: 'Hindistan cevizli kek', price: '14 AZN' },
      { name_az: 'Ballı tort', name_ru: 'Медовик', name_en: 'Honey cake', name_tr: 'Ballı pasta', price: '14 AZN' },
      { name_az: 'Krem brule', name_ru: 'Крем-брюле', name_en: 'Crème brûlée', name_tr: 'Krem brule', price: '14 AZN', is_gluten_free: true },
      { name_az: 'Fıstıqlı tart', name_ru: 'Фисташковый тарт', name_en: 'Pistachio tart', name_tr: 'Fıstıklı tart', price: '14 AZN' },
      /* NATIONAL DELIGHTS */
      { name_az: 'Paxlava (1 ədəd)', name_ru: 'Пахлава (1 шт)', name_en: 'Baklava (1 pcs)', name_tr: 'Baklava (1 adet)', price: '5 AZN' },
      { name_az: 'Qarışıq gelato (3 ədəd)', name_ru: 'Микс гелато (3 шарика)', name_en: 'Mixed gelato (3 scoop)', name_tr: 'Karışık gelato (3 top)', price: '12 AZN', is_gluten_free: true },
      { name_az: 'Şokoladlı xurma (3 ədəd)', name_ru: 'Шоколадные финики (3 шт)', name_en: 'Chocolate dates (3 pcs)', name_tr: 'Çikolatalı hurma (3 adet)', price: '4 AZN', is_sugar_free: true },
      { name_az: 'Moçi (1 ədəd)', name_ru: 'Моти (1 шт)', name_en: 'Mochi (1 pcs)', name_tr: 'Mochi (1 adet)', price: '12 AZN', is_gluten_free: true },
      /* THE FINAL TOUCH */
      { name_az: 'Xüsusi burma keyki', name_ru: 'Особый торт Бурма', name_en: 'Special burma cake', name_tr: 'Özel Burma keki', price: '14 AZN' },
      { name_az: 'Gluten-free keyk', name_ru: 'Безглютеновый кекс', name_en: 'Gluten-free cake', name_tr: 'Glutensiz kek', price: '14 AZN', is_gluten_free: true },
    ],
  },
]

/** @deprecated Use trpc.menu.getMenu({ tab: "beverage" }) instead. Kept for legacy pages still migrating. */
export const beverageData: MenuCategory[] = [
  {
    id: 'cocktails_signature',
    title_az: 'İMZA KOKTEYLLƏR',
    title_ru: 'ФИРМЕННЫЕ КОКТЕЙЛИ',
    title_en: 'SIGNATURE COCKTAILS',
    title_tr: 'İmza Kokteyller',
    sortOrder: 10,
    items: [
      { name_az: 'Chica & Jimador', name_ru: 'Chica & Jimador', name_en: 'Chica & Jimador', name_tr: 'Chica & Jimador', price: '13 AZN' },
      { name_az: 'City Fizz', name_ru: 'City Fizz', name_en: 'City Fizz', name_tr: 'City Fizz', price: '13 AZN' },
      { name_az: 'Pie Tai', name_ru: 'Pie Tai', name_en: 'Pie Tai', name_tr: 'Pie Tai', price: '13 AZN' },
      { name_az: 'Woody', name_ru: 'Woody', name_en: 'Woody', name_tr: 'Woody', price: '13 AZN' },
      { name_az: 'Bitter Crunch', name_ru: 'Bitter Crunch', name_en: 'Bitter Crunch', name_tr: 'Bitter Crunch', price: '15 AZN' },
      { name_az: 'Dr. Fashion', name_ru: 'Dr. Fashion', name_en: 'Dr. Fashion', name_tr: 'Dr. Fashion', price: '15 AZN' },
      { name_az: 'Jackie-Pookie', name_ru: 'Jackie-Pookie', name_en: 'Jackie-Pookie', name_tr: 'Jackie-Pookie', price: '15 AZN' },
      { name_az: 'Lily Spritz', name_ru: 'Lily Spritz', name_en: 'Lily Spritz', name_tr: 'Lily Spritz', price: '15 AZN' },
      { name_az: 'Spoted Mai Tai', name_ru: 'Spoted Mai Tai', name_en: 'Spoted Mai Tai', name_tr: 'Spoted Mai Tai', price: '15 AZN' },
    ],
  },
  {
    id: 'cocktails_classic',
    title_az: 'KLASSIK KOKTEYLLƏR',
    title_ru: 'КЛАССИЧЕСКИЕ КОКТЕЙЛИ',
    title_en: 'CLASSIC COCKTAILS',
    title_tr: 'Klasik Kokteyller',
    sortOrder: 20,
    items: [
      { name_az: 'Mango espresso martini', name_ru: 'Манго эспрессо мартини', name_en: 'Mango espresso martini', name_tr: 'Mango espresso martini', price: '13 AZN' },
      { name_az: 'Pornstar martini', name_ru: 'Pornstar мартини', name_en: 'Pornstar martini', name_tr: 'Pornstar martini', price: '13 AZN' },
      { name_az: 'Aperol Spritz', name_ru: 'Aperol Spritz', name_en: 'Aperol Spritz', name_tr: 'Aperol Spritz', price: '15 AZN' },
      { name_az: 'Negroni', name_ru: 'Negroni', name_en: 'Negroni', name_tr: 'Negroni', price: '15 AZN' },
      { name_az: 'Long Island iced tea', name_ru: 'Лонг Айленд айс ти', name_en: 'Long Island iced tea', name_tr: 'Long Island iced tea', price: '18 AZN' },
    ],
  },
  {
    id: 'mocktails_signature',
    title_az: 'İMZA MOKTEYLLƏR',
    title_ru: 'ФИРМЕННЫЕ МОКТЕЙЛИ',
    title_en: 'SIGNATURE MOCKTAILS',
    title_tr: 'İmza Mocktailler',
    sortOrder: 30,
    items: [
      { name_az: 'Cucu Hugo Collins', name_ru: 'Cucu Hugo Collins', name_en: 'Cucu Hugo Collins', name_tr: 'Cucu Hugo Collins', price: '11 AZN' },
      { name_az: 'Donna Sour', name_ru: 'Donna Sour', name_en: 'Donna Sour', name_tr: 'Donna Sour', price: '11 AZN' },
      { name_az: 'Tahiti Tonic', name_ru: 'Tahiti Tonic', name_en: 'Tahiti Tonic', name_tr: 'Tahiti Tonic', price: '11 AZN' },
      { name_az: 'Virgin Pornstar', name_ru: 'Virgin Pornstar', name_en: 'Virgin Pornstar', name_tr: 'Virgin Pornstar', price: '11 AZN' },
    ],
  },
  {
    id: 'beer',
    title_az: 'PİVƏ',
    title_ru: 'ПИВО',
    title_en: 'BEER',
    title_tr: 'Bira',
    sortOrder: 60,
    items: [
      { name_az: 'Asahi Beer Super Dry 330ml', name_ru: 'Asahi Beer Super Dry 330ml', name_en: 'Asahi Beer Super Dry 330ml', name_tr: 'Asahi Beer Super Dry 330ml', price: '11 AZN' },
      { name_az: 'Paulaner 0.0% 500ml', name_ru: 'Paulaner 0.0% 500ml', name_en: 'Paulaner 0.0% 500ml', name_tr: 'Paulaner 0.0% 500ml', price: '13 AZN' },
      { name_az: 'Heineken Original 330ml', name_ru: 'Heineken Original 330ml', name_en: 'Heineken Original 330ml', name_tr: 'Heineken Original 330ml', price: '14 AZN' },
      { name_az: 'Paulaner Naturtrub 500ml', name_ru: 'Paulaner Naturtrub 500ml', name_en: 'Paulaner Naturtrub 500ml', name_tr: 'Paulaner Naturtrub 500ml', price: '14 AZN' },
    ],
  },
  {
    id: 'champagne',
    title_az: 'ŞAMPAN',
    title_ru: 'ШАМПАНСКОЕ',
    title_en: 'CHAMPAGNE',
    title_tr: 'Şampanya',
    sortOrder: 100,
    items: [
      { name_az: 'Bottega Brut (125ml)', name_ru: 'Bottega Brut (125ml)', name_en: 'Bottega Brut (125ml)', name_tr: 'Bottega Brut (125ml)', price: '15 AZN' },
      { name_az: 'Bottega Brut', name_ru: 'Bottega Brut', name_en: 'Bottega Brut', name_tr: 'Bottega Brut', price: '60 AZN' },
      { name_az: 'FA Valley, Petnat, Xaçmaz', name_ru: 'FA Valley, Petnat, Хачмаз', name_en: 'FA Valley, Petnat, Khachmaz', name_tr: 'FA Valley, Petnat, Khachmaz', price: '80 AZN' },
      { name_az: 'Doudet Naudin', name_ru: 'Doudet Naudin', name_en: 'Doudet Naudin', name_tr: 'Doudet Naudin', price: '210 AZN' },
      { name_az: 'Mumm Cordon', name_ru: 'Mumm Cordon', name_en: 'Mumm Cordon', name_tr: 'Mumm Cordon', price: '250 AZN' },
      { name_az: 'Moet & Chandon', name_ru: 'Moet & Chandon', name_en: 'Moet & Chandon', name_tr: 'Moet & Chandon', price: '375 AZN' },
      { name_az: 'Moet & Chandon Rose', name_ru: 'Moet & Chandon Rose', name_en: 'Moet & Chandon Rose', name_tr: 'Moet & Chandon Rose', price: '445 AZN' },
    ],
  },
  {
    id: 'wine_white_rose',
    title_az: 'AĞ VƏ ROZE ŞƏRAB',
    title_ru: 'БЕЛОЕ И РОЗОВОЕ ВИНО',
    title_en: 'WHITE & ROSÉ WINE',
    title_tr: 'Beyaz & Rose Şarap',
    sortOrder: 40,
    items: [
      { name_az: 'FA Valley, Amore, Rose (125ml)', name_ru: 'FA Valley, Amore, Rose (125ml)', name_en: 'FA Valley, Amore, Rose (125ml)', name_tr: 'FA Valley, Amore, Rose (125ml)', price: '15 AZN' },
      { name_az: 'Meysari Sedef (125ml)', name_ru: 'Meysari Sedef (125ml)', name_en: 'Meysari Sedef (125ml)', name_tr: 'Meysari Sedef (125ml)', price: '15 AZN' },
      { name_az: 'Meysari Sedef', name_ru: 'Meysari Sedef', name_en: 'Meysari Sedef', name_tr: 'Meysari Sedef', price: '60 AZN' },
      { name_az: 'Whalebone Sauvignon Blanc', name_ru: 'Whalebone Sauvignon Blanc', name_en: 'Whalebone Sauvignon Blanc', name_tr: 'Whalebone Sauvignon Blanc', price: '110 AZN' },
      { name_az: 'Marrone Moscato DOCG', name_ru: 'Marrone Moscato DOCG', name_en: 'Marrone Moscato DOCG', name_tr: 'Marrone Moscato DOCG', price: '250 AZN' },
    ],
  },
  {
    id: 'wine_red',
    title_az: 'QIRMIZI ŞƏRAB',
    title_ru: 'КРАСНОЕ ВИНО',
    title_en: 'RED WINE',
    title_tr: 'Kırmızı Şarap',
    sortOrder: 50,
    items: [
      { name_az: 'FA Valley, Amore, Xaçmaz, Rose', name_ru: 'FA Valley, Amore, Хачмаз, Rose', name_en: 'FA Valley, Amore, Khachmaz, Rose', name_tr: 'FA Valley, Amore, Khachmaz, Rose', price: '60 AZN' },
      { name_az: 'Meysari Billuri', name_ru: 'Meysari Billuri', name_en: 'Meysari Billuri', name_tr: 'Meysari Billuri', price: '60 AZN' },
      { name_az: 'Meysari Marjan', name_ru: 'Meysari Marjan', name_en: 'Meysari Marjan', name_tr: 'Meysari Marjan', price: '60 AZN' },
      { name_az: 'Meysari Innabi', name_ru: 'Meysari Innabi', name_en: 'Meysari Innabi', name_tr: 'Meysari Innabi', price: '60 AZN' },
      { name_az: 'Meysari Makhmari (125ml)', name_ru: 'Meysari Makhmari (125ml)', name_en: 'Meysari Makhmari (125ml)', name_tr: 'Meysari Makhmari (125ml)', price: '15 AZN' },
      { name_az: 'Meysari Makhmari', name_ru: 'Meysari Makhmari', name_en: 'Meysari Makhmari', name_tr: 'Meysari Makhmari', price: '70 AZN' },
      { name_az: 'Marrone, Barbaresco DOCG', name_ru: 'Marrone, Barbaresco DOCG', name_en: 'Marrone, Barbaresco DOCG', name_tr: 'Marrone, Barbaresco DOCG', price: '125 AZN' },
      { name_az: 'FA Valley, Fratello 2020, Red Dry', name_ru: 'FA Valley, Fratello 2020, Red Dry', name_en: 'FA Valley, Fratello 2020, Red Dry', name_tr: 'FA Valley, Fratello 2020, Red Dry', price: '170 AZN' },
      { name_az: 'FA Valley, Nessun Dorma 2022, Red Dry', name_ru: 'FA Valley, Nessun Dorma 2022, Red Dry', name_en: 'FA Valley, Nessun Dorma 2022, Red Dry', name_tr: 'FA Valley, Nessun Dorma 2022, Red Dry', price: '170 AZN' },
      { name_az: 'Brunello di Montalcino', name_ru: 'Brunello di Montalcino', name_en: 'Brunello di Montalcino', name_tr: 'Brunello di Montalcino', price: '420 AZN' },
    ],
  },
  {
    id: 'whiskey',
    title_az: 'VİSKİ (40ml)',
    title_ru: 'ВИСКИ (40ml)',
    title_en: 'WHISKEY (40ml)',
    title_tr: 'Viski (40ml)',
    sortOrder: 70,
    items: [
      { name_az: "Jack Daniel's No 7", name_ru: "Jack Daniel's No 7", name_en: "Jack Daniel's No 7", price: '12 AZN' },
      { name_az: "Jack Daniel's Apple", name_ru: "Jack Daniel's Apple", name_en: "Jack Daniel's Apple", price: '13 AZN' },
      { name_az: "Jack Daniel's Honey", name_ru: "Jack Daniel's Honey", name_en: "Jack Daniel's Honey", price: '13 AZN' },
      { name_az: 'Bulleit Bourbon', name_ru: 'Bulleit Bourbon', name_en: 'Bulleit Bourbon', name_tr: 'Bulleit Bourbon', price: '14 AZN' },
      { name_az: 'Jameson', name_ru: 'Jameson', name_en: 'Jameson', name_tr: 'Jameson', price: '14 AZN' },
      { name_az: 'Wild Turkey 81', name_ru: 'Wild Turkey 81', name_en: 'Wild Turkey 81', name_tr: 'Wild Turkey 81', price: '14 AZN' },
      { name_az: 'JW Black Label', name_ru: 'JW Black Label', name_en: 'JW Black Label', name_tr: 'JW Black Label', price: '14 AZN' },
      { name_az: "Jack Daniel's Single Barrel", name_ru: "Jack Daniel's Single Barrel", name_en: "Jack Daniel's Single Barrel", price: '16 AZN' },
      { name_az: 'Singleton of Dufftown', name_ru: 'Singleton of Dufftown', name_en: 'Singleton of Dufftown', name_tr: 'Singleton of Dufftown', price: '16 AZN' },
      { name_az: 'Glenfiddich 12 YO', name_ru: 'Glenfiddich 12 YO', name_en: 'Glenfiddich 12 YO', name_tr: 'Glenfiddich 12 YO', price: '18 AZN' },
      { name_az: 'JW Gold Label Reserve', name_ru: 'JW Gold Label Reserve', name_en: 'JW Gold Label Reserve', name_tr: 'JW Gold Label Reserve', price: '18 AZN' },
      { name_az: 'Monkey Shoulder', name_ru: 'Monkey Shoulder', name_en: 'Monkey Shoulder', name_tr: 'Monkey Shoulder', price: '18 AZN' },
      { name_az: 'Glenfiddich 15 YO', name_ru: 'Glenfiddich 15 YO', name_en: 'Glenfiddich 15 YO', name_tr: 'Glenfiddich 15 YO', price: '22 AZN' },
      { name_az: 'Chivas Regal 18 YO', name_ru: 'Chivas Regal 18 YO', name_en: 'Chivas Regal 18 YO', name_tr: 'Chivas Regal 18 YO', price: '25 AZN' },
      { name_az: 'Macallan Double Cask 15 YO', name_ru: 'Macallan Double Cask 15 YO', name_en: 'Macallan Double Cask 15 YO', name_tr: 'Macallan Double Cask 15 YO', price: '60 AZN' },
      { name_az: 'JW Blue Label', name_ru: 'JW Blue Label', name_en: 'JW Blue Label', name_tr: 'JW Blue Label', price: '66 AZN' },
    ],
  },
  {
    id: 'rum',
    title_az: 'ROM (40ml)',
    title_ru: 'РОМ (40ml)',
    title_en: 'RUM (40ml)',
    title_tr: 'Rom (40ml)',
    sortOrder: 120,
    items: [
      { name_az: 'Bacardi Carta Blanca', name_ru: 'Bacardi Carta Blanca', name_en: 'Bacardi Carta Blanca', name_tr: 'Bacardi Carta Blanca', price: '8 AZN' },
      { name_az: 'Bacardi Carta Negra', name_ru: 'Bacardi Carta Negra', name_en: 'Bacardi Carta Negra', name_tr: 'Bacardi Carta Negra', price: '8 AZN' },
      { name_az: 'Captain Morgan Dark', name_ru: 'Captain Morgan Dark', name_en: 'Captain Morgan Dark', name_tr: 'Captain Morgan Dark', price: '12 AZN' },
      { name_az: 'Captain Morgan Spiced Gold', name_ru: 'Captain Morgan Spiced Gold', name_en: 'Captain Morgan Spiced Gold', name_tr: 'Captain Morgan Spiced Gold', price: '12 AZN' },
      { name_az: 'Captain Morgan White', name_ru: 'Captain Morgan White', name_en: 'Captain Morgan White', name_tr: 'Captain Morgan White', price: '12 AZN' },
    ],
  },
  {
    id: 'vodka',
    title_az: 'VODKA (40ml)',
    title_ru: 'ВОДКА (40ml)',
    title_en: 'VODKA (40ml)',
    title_tr: 'Votka (40ml)',
    sortOrder: 80,
    items: [
      { name_az: 'Finlandia', name_ru: 'Finlandia', name_en: 'Finlandia', name_tr: 'Finlandia', price: '10 AZN' },
      { name_az: 'Graddau 54', name_ru: 'Graddau 54', name_en: 'Graddau 54', name_tr: 'Graddau 54', price: '10 AZN' },
      { name_az: 'Ciroc', name_ru: 'Ciroc', name_en: 'Ciroc', name_tr: 'Ciroc', price: '15 AZN' },
      { name_az: 'Grey Goose', name_ru: 'Grey Goose', name_en: 'Grey Goose', name_tr: 'Grey Goose', price: '17 AZN' },
      { name_az: 'Beluga Noble', name_ru: 'Beluga Noble', name_en: 'Beluga Noble', name_tr: 'Beluga Noble', price: '18 AZN' },
      { name_az: 'Belvedere', name_ru: 'Belvedere', name_en: 'Belvedere', name_tr: 'Belvedere', price: '19 AZN' },
    ],
  },
  {
    id: 'gin',
    title_az: 'CİN (40ml)',
    title_ru: 'ДЖИН (40ml)',
    title_en: 'GIN (40ml)',
    title_tr: 'Cin (40ml)',
    sortOrder: 110,
    items: [
      { name_az: 'Tanqueray London Dry', name_ru: 'Tanqueray London Dry', name_en: 'Tanqueray London Dry', name_tr: 'Tanqueray London Dry', price: '13 AZN' },
      { name_az: 'Tanqueray No Ten', name_ru: 'Tanqueray No Ten', name_en: 'Tanqueray No Ten', name_tr: 'Tanqueray No Ten', price: '13 AZN' },
      { name_az: 'Gin Mare', name_ru: 'Gin Mare', name_en: 'Gin Mare', name_tr: 'Gin Mare', price: '17 AZN' },
      { name_az: "Hendrick's", name_ru: "Hendrick's", name_en: "Hendrick's", price: '18 AZN' },
    ],
  },
  {
    id: 'tequila',
    title_az: 'TEKİLA (40ml)',
    title_ru: 'ТЕКИЛА (40ml)',
    title_en: 'TEQUILA (40ml)',
    title_tr: 'Tekila (40ml)',
    sortOrder: 90,
    items: [
      { name_az: 'Patron Reposado', name_ru: 'Patron Reposado', name_en: 'Patron Reposado', name_tr: 'Patron Reposado', price: '21 AZN' },
      { name_az: 'Patron Blanco', name_ru: 'Patron Blanco', name_en: 'Patron Blanco', name_tr: 'Patron Blanco', price: '21 AZN' },
      { name_az: 'Don Julio Reposado', name_ru: 'Don Julio Reposado', name_en: 'Don Julio Reposado', name_tr: 'Don Julio Reposado', price: '25 AZN' },
      { name_az: 'Don Julio Blanco', name_ru: 'Don Julio Blanco', name_en: 'Don Julio Blanco', name_tr: 'Don Julio Blanco', price: '25 AZN' },
      { name_az: 'Don Julio 1942', name_ru: 'Don Julio 1942', name_en: 'Don Julio 1942', name_tr: 'Don Julio 1942', price: '70 AZN' },
    ],
  },
  {
    id: 'cognac',
    title_az: 'KONYAK (40ml)',
    title_ru: 'КОНЬЯК (40ml)',
    title_en: 'COGNAC (40ml)',
    title_tr: 'Konyak (40ml)',
    sortOrder: 130,
    items: [
      { name_az: 'Hennessy VSOP', name_ru: 'Hennessy VSOP', name_en: 'Hennessy VSOP', name_tr: 'Hennessy VSOP', price: '35 AZN' },
      { name_az: 'Hennessy XO', name_ru: 'Hennessy XO', name_en: 'Hennessy XO', name_tr: 'Hennessy XO', price: '100 AZN' },
    ],
  },
  {
    id: 'liqueur',
    title_az: 'LİKÖR (40ml)',
    title_ru: 'ЛИКЁР (40ml)',
    title_en: 'LIQUEUR (40ml)',
    title_tr: 'Likör (40ml)',
    sortOrder: 140,
    items: [
      { name_az: 'Kahlua', name_ru: 'Kahlua', name_en: 'Kahlua', name_tr: 'Kahlua', price: '8 AZN' },
      { name_az: 'Aperol', name_ru: 'Aperol', name_en: 'Aperol', name_tr: 'Aperol', price: '9 AZN' },
      { name_az: 'Campari', name_ru: 'Campari', name_en: 'Campari', name_tr: 'Campari', price: '9 AZN' },
      { name_az: 'Baileys Original', name_ru: 'Baileys Original', name_en: 'Baileys Original', name_tr: 'Baileys Original', price: '11 AZN' },
      { name_az: 'Jagermeister', name_ru: 'Jagermeister', name_en: 'Jagermeister', name_tr: 'Jagermeister', price: '11 AZN' },
      { name_az: 'Martini Bianco', name_ru: 'Martini Bianco', name_en: 'Martini Bianco', name_tr: 'Martini Bianco', price: '11 AZN' },
      { name_az: 'Martini Extra Dry', name_ru: 'Martini Extra Dry', name_en: 'Martini Extra Dry', name_tr: 'Martini Extra Dry', price: '11 AZN' },
      { name_az: 'Martini Fierro', name_ru: 'Martini Fierro', name_en: 'Martini Fierro', name_tr: 'Martini Fierro', price: '11 AZN' },
      { name_az: 'Martini Rosso', name_ru: 'Martini Rosso', name_en: 'Martini Rosso', name_tr: 'Martini Rosso', price: '11 AZN' },
      { name_az: 'Jagermeister Manifest', name_ru: 'Jagermeister Manifest', name_en: 'Jagermeister Manifest', name_tr: 'Jagermeister Manifest', price: '15 AZN' },
    ],
  },
  {
    id: 'coffee',
    title_az: 'QƏHVƏ',
    title_ru: 'КОФЕ',
    title_en: 'COFFEE',
    title_tr: 'Kahve',
    sortOrder: 160,
    items: [
      { name_az: 'Espresso', name_ru: 'Эспрессо', name_en: 'Espresso', name_tr: 'Espresso', price: '4.5 AZN' },
      { name_az: 'Türk qəhvəsi', name_ru: 'Турецкий кофе', name_en: 'Turkish coffee', name_tr: 'Türk kahvesi', price: '5.5 AZN' },
      { name_az: 'Americano', name_ru: 'Американо', name_en: 'Americano', name_tr: 'Americano', price: '7 AZN' },
      { name_az: 'Double espresso', name_ru: 'Двойной эспрессо', name_en: 'Double espresso', name_tr: 'Çift espresso', price: '7 AZN' },
      { name_az: 'Cappuccino', name_ru: 'Капучино', name_en: 'Cappuccino', name_tr: 'Cappuccino', price: '8 AZN' },
      { name_az: 'Flat White', name_ru: 'Флэт уайт', name_en: 'Flat White', name_tr: 'Flat White', price: '8 AZN' },
      { name_az: 'Latte', name_ru: 'Латте', name_en: 'Latte', name_tr: 'Latte', price: '8 AZN' },
      { name_az: 'Spanish Latte', name_ru: 'Spanish Latte', name_en: 'Spanish Latte', name_tr: 'Spanish Latte', price: '8 AZN' },
      { name_az: 'Raff Classic', name_ru: 'Raff Classic', name_en: 'Raff Classic', name_tr: 'Raff Classic', price: '9 AZN' },
    ],
  },
  {
    id: 'tea',
    title_az: 'ÇAY',
    title_ru: 'ЧАЙ',
    title_en: 'TEA',
    title_tr: 'Çay',
    sortOrder: 170,
    items: [
      { name_az: 'Çay stəkanda', name_ru: 'Чай в стакане', name_en: 'Tea in glass', name_tr: 'Bardak çay', price: '7 AZN' },
      { name_az: 'Lənkəran çayı', name_ru: 'Ленкоранский чай', name_en: 'Lankaran tea', name_tr: 'Lenkeran çayı', price: '18 AZN' },
      { name_az: 'Chouchou & Loulou', name_ru: 'Chouchou & Loulou', name_en: 'Chouchou & Loulou', name_tr: 'Chouchou & Loulou', price: '20 AZN' },
      { name_az: 'Douce Nuit', name_ru: 'Douce Nuit', name_en: 'Douce Nuit', name_tr: 'Douce Nuit', price: '20 AZN' },
      { name_az: 'La Tete dans les Etoiles', name_ru: 'La Tete dans les Etoiles', name_en: 'La Tete dans les Etoiles', name_tr: 'La Tete dans les Etoiles', price: '20 AZN' },
      { name_az: 'Le Temps Present Bio', name_ru: 'Le Temps Present Bio', name_en: 'Le Temps Present Bio', name_tr: 'Le Temps Present Bio', price: '20 AZN' },
      { name_az: 'Les Cloches Sonnent', name_ru: 'Les Cloches Sonnent', name_en: 'Les Cloches Sonnent', name_tr: 'Les Cloches Sonnent', price: '20 AZN' },
      { name_az: 'Cascara Tea', name_ru: 'Cascara Tea', name_en: 'Cascara Tea', name_tr: 'Cascara Tea', price: '20 AZN' },
      { name_az: 'Marcel de Provence', name_ru: 'Marcel de Provence', name_en: 'Marcel de Provence', name_tr: 'Marcel de Provence', price: '20 AZN' },
      { name_az: 'Mon Beau Sapin', name_ru: 'Mon Beau Sapin', name_en: 'Mon Beau Sapin', name_tr: 'Mon Beau Sapin', price: '20 AZN' },
      { name_az: 'Pain d\'Epice', name_ru: 'Pain d\'Epice', name_en: 'Pain d\'Epice', name_tr: 'Pain d\'Epice', price: '20 AZN' },
      { name_az: 'Pomme Verte', name_ru: 'Pomme Verte', name_en: 'Pomme Verte', name_tr: 'Pomme Verte', price: '20 AZN' },
      { name_az: 'Rouge Ananas', name_ru: 'Rouge Ananas', name_en: 'Rouge Ananas', name_tr: 'Rouge Ananas', price: '20 AZN' },
      { name_az: 'Si T\'es Sage', name_ru: 'Si T\'es Sage', name_en: 'Si T\'es Sage', name_tr: 'Si T\'es Sage', price: '20 AZN' },
      { name_az: 'The de la Chance', name_ru: 'The de la Chance', name_en: 'The de la Chance', name_tr: 'The de la Chance', price: '20 AZN' },
      { name_az: 'Toujours La', name_ru: 'Toujours La', name_en: 'Toujours La', name_tr: 'Toujours La', price: '20 AZN' },
      { name_az: 'Vachement Sympa', name_ru: 'Vachement Sympa', name_en: 'Vachement Sympa', name_tr: 'Vachement Sympa', price: '20 AZN' },
      { name_az: 'Coco Givrees', name_ru: 'Coco Givrees', name_en: 'Coco Givrees', name_tr: 'Coco Givrees', price: '25 AZN' },
      { name_az: 'Rose en Sucre', name_ru: 'Rose en Sucre', name_en: 'Rose en Sucre', name_tr: 'Rose en Sucre', price: '25 AZN' },
      { name_az: 'Energie du Yogi Bio', name_ru: 'Energie du Yogi Bio', name_en: 'Energie du Yogi Bio', name_tr: 'Energie du Yogi Bio', price: '30 AZN' },
      { name_az: 'Jardin Emeraude Bio', name_ru: 'Jardin Emeraude Bio', name_en: 'Jardin Emeraude Bio', name_tr: 'Jardin Emeraude Bio', price: '30 AZN' },
      { name_az: 'Le Temps des Cerises', name_ru: 'Le Temps des Cerises', name_en: 'Le Temps des Cerises', name_tr: 'Le Temps des Cerises', price: '30 AZN' },
      { name_az: 'Ma Bonne Etoile', name_ru: 'Ma Bonne Etoile', name_en: 'Ma Bonne Etoile', name_tr: 'Ma Bonne Etoile', price: '30 AZN' },
      { name_az: 'Sucre d\'Orge', name_ru: 'Sucre d\'Orge', name_en: 'Sucre d\'Orge', name_tr: 'Sucre d\'Orge', price: '30 AZN' },
    ],
  },
  {
    id: 'cold_drinks',
    title_az: 'SOYUQ İÇKİLƏR',
    title_ru: 'БЕЗАЛКОГОЛЬНЫЕ НАПИТКИ',
    title_en: 'SOFT DRINKS',
    title_tr: 'Soğuk İçecekler',
    sortOrder: 150,
    items: [
      { name_az: 'Coca-Cola / Coca-Cola Zero / Fanta / Sprite 330ml', name_ru: 'Coca-Cola / Coca-Cola Zero / Fanta / Sprite 330ml', name_en: 'Coca-Cola / Coca-Cola Zero / Fanta / Sprite 330ml', name_tr: 'Coca-Cola / Coca-Cola Zero / Fanta / Sprite 330ml', price: '5.5 AZN' },
      { name_az: 'Schweppes Tonic', name_ru: 'Schweppes Tonic', name_en: 'Schweppes Tonic', name_tr: 'Schweppes Tonic', price: '5.5 AZN' },
      { name_az: 'Red Bull', name_ru: 'Red Bull', name_en: 'Red Bull', name_tr: 'Red Bull', price: '8 AZN' },
      { name_az: 'Sirab Premium Qazsız / Qazlı', name_ru: 'Sirab Premium Still / Sparkling', name_en: 'Sirab Premium Still / Sparkling', name_tr: 'Sirab Premium Gazlı / Gazsız', price: '4 AZN' },
      { name_az: 'Istisu Qazlı', name_ru: 'Istisu Sparkling', name_en: 'Istisu Sparkling', name_tr: 'Istisu Gazlı', price: '5.5 AZN' },
      { name_az: 'Evian Qazsız', name_ru: 'Evian Still', name_en: 'Evian Still', name_tr: 'Evian Gazsız', price: '6.5 AZN' },
      { name_az: 'San Pellegrino Qazlı', name_ru: 'San Pellegrino Sparkling', name_en: 'San Pellegrino Sparkling', name_tr: 'San Pellegrino Gazlı', price: '6.5 AZN' },
    ],
  },
]

/** @deprecated Use trpc.menu.getMenu({ tab: "shisha" }) instead. Kept for legacy pages still migrating. */
export const shishaData: ShishaData = {
  hookahs: [
    { name_az: 'Wookah', name_ru: 'Wookah', name_en: 'Wookah', name_tr: 'Wookah', price: '100 AZN' },
    { name_az: 'Hooky', name_ru: 'Hooky', name_en: 'Hooky', name_tr: 'Hooky', price: '85 AZN' },
    { name_az: 'Quasar', name_ru: 'Quasar', name_en: 'Quasar', name_tr: 'Quasar', price: '75 AZN' },
  ],
  bestSellers: [
    'Sherbetli — Lime Spiced Peach',
    'Sherbetli — Ice Berry',
    'Sherbetli — Feijoa',
    'Al Fakher — Grape',
    'Azure Gold Line — Lychee',
    'Musthave — Tropic Juice',
    'Starline — Pineapple',
    'White Angel — Original',
    'Adalya — N1',
  ],
  premium: [
    'Palitra Classic',
    'Darkside',
    'Sebero',
    'Musthave',
    'Sarma',
    'Chabacco',
    'Xuligan',
    'Deus',
    'Bonche',
  ],
  classic: [
    'Sherbetli',
    'Starline',
    'Al Fakher',
    'Blackburn',
    'Adalya',
    'Element',
    'Nash',
    'Everest',
  ],
}
