#!/usr/bin/env tsx
/* Seed default SEO entries into seo_settings table from PAGE_TEMPLATES */

import "dotenv/config";
import { getDb } from "../api/queries/connection";
import { seoSettings } from "../db/schema";
import { eq } from "drizzle-orm";

const PAGES = [
  { id: "home", titleAz: "The Woo White City | Bakı Premium Restoran, Lounge və Qəlyan", titleRu: "The Woo White City | Премиальный ресторан, лаунж и кальян в Баку", titleEn: "The Woo White City | Premium Restaurant, Lounge & Shisha in Baku", titleTr: "The Woo White City | Bakü Premium Restoran, Lounge ve Nargile", descAz: "The Woo White City — White City-də yerləşən premium restoran və lounge. Müasir Azərbaycan mətbəxi, Avropa ləzzətləri, imza kokteyllər və premium qəlyan təcrübəsi.", descRu: "The Woo White City — премиальный ресторан и лаунж в White City, Баку. Современная азербайджанская кухня, европейские блюда, фирменные коктейли и премиальный кальян.", descEn: "The Woo White City is a premium restaurant and lounge in White City, Baku, offering modern Azerbaijani cuisine, European dishes, signature cocktails and premium shisha.", descTr: "The Woo White City, Bakü White City'de modern Azerbaycan mutfağı, Avrupa lezzetleri, imza kokteyller ve premium nargile deneyimi sunan premium bir restoran ve lounge'dur.", kwAz: "restoran bakı, lounge bakı, premium restoran, qəlyan bakı, kokteyl bar, the woo white city", kwRu: "ресторан баку, лаунж баку, премиальный ресторан, кальян баку, коктейль бар", kwEn: "baku restaurant, baku lounge, premium restaurant, shisha baku, cocktail bar", kwTr: "baku restoran, baku lounge, premium restoran, nargile baku, kokteyl bar" },
  { id: "menu", titleAz: "Menyu | The Woo White City — Yemək, İçki və Qəlyan", titleRu: "Меню | The Woo White City — Еда, Напитки и Кальян", titleEn: "Menu | The Woo White City — Food, Beverages & Shisha", titleTr: "Menü | The Woo White City — Yemek, İçecek ve Nargile", descAz: "The Woo White City menyusu — müasir Azərbaycan və Avropa yeməkləri, imza kokteyllər, geniş şərab seçimi və premium qəlyan çeşidləri.", descRu: "Меню The Woo White City — современная азербайджанская и европейская кухня, фирменные коктейли, богатая винная карта и премиальный кальян.", descEn: "The Woo White City menu — modern Azerbaijani and European cuisine, signature cocktails, extensive wine selection and premium shisha varieties.", descTr: "The Woo White City menüsü — modern Azerbaycan ve Avrupa mutfağı, imza kokteyller, geniş şarap seçimi ve premium nargile çeşitleri.", kwAz: "menyu bakı, yemek menyusu, içki menyu, qəlyan menyu, restoran menyu", kwRu: "меню баку, меню ресторан, кальян меню, коктейли баку", kwEn: "menu baku, food menu, beverage menu, shisha menu, restaurant menu", kwTr: "menü baku, yemek menüsü, içecek menüsü, nargile menüsü, restoran menüsü" },
  { id: "food", titleAz: "Yemek Menyusu | The Woo White City — A La Carte", titleRu: "Меню еды | The Woo White City — A La Carte", titleEn: "Food Menu | The Woo White City — A La Carte", titleTr: "Yemek Menüsü | The Woo White City — A La Carte", descAz: "A La Carte menyumuz — müasir Azərbaycan mətbəxi, odun fırını pizzalar, ət yeməkləri, dəniz məhsulları və vegetarian seçimləri.", descRu: "Меню A La Carte — современная азербайджанская кухня, пицца из дровяной печи, мясные блюда, морепродукты и вегетарианские блюда.", descEn: "Our A La Carte menu — modern Azerbaijani cuisine, wood-fired pizzas, meat dishes, seafood and vegetarian options.", descTr: "A La Carte menümüz — modern Azerbaycan mutfağı, odun fırını pizzalar, et yemekleri, deniz ürünleri ve vejetaryen seçenekler.", kwAz: "a la carte bakı, yemek menyusu, azərbaycan mətbəxi, pizza odun fırını", kwRu: "a la carte баку, меню еды, азербайджанская кухня, пицца дровяная печь", kwEn: "a la carte baku, food menu, azerbaijani cuisine, wood fired pizza", kwTr: "a la carte baku, yemek menüsü, azerbaycan mutfağı, odun fırını pizza" },
  { id: "beverage", titleAz: "İçki Menyusu | The Woo White City — Kokteyllər və Şərablar", titleRu: "Меню напитков | The Woo White City — Коктейли и Вино", titleEn: "Beverage Menu | The Woo White City — Cocktails & Wine", titleTr: "İçecek Menüsü | The Woo White City — Kokteyller ve Şaraplar", descAz: "İçki menyumuz — imza kokteyllər, klassik kokteyllər, geniş şərab seçimi, premium spirtli içkilər və təravətli mocktaillər.", descRu: "Меню напитков — фирменные коктейли, классические коктейли, богатая винная карта, премиум алкоголь и освежающие моктейли.", descEn: "Our beverage menu — signature cocktails, classic cocktails, extensive wine selection, premium spirits and refreshing mocktails.", descTr: "İçecek menümüz — imza kokteyller, klasik kokteyller, geniş şarap seçimi, premium alkollü içecekler ve ferahlatıcı mocktailler.", kwAz: "kokteyl bar bakı, içki menyusu, şərab seçimi, mocktail, premium içki", kwRu: "коктейль бар баку, меню напитков, винная карта, моктейли", kwEn: "cocktail bar baku, beverage menu, wine selection, mocktail, premium spirits", kwTr: "kokteyl bar baku, içecek menüsü, şarap seçimi, mocktail, premium içki" },
  { id: "shisha", titleAz: "Qəlyan Menyusu | The Woo White City — Premium Qəlyan", titleRu: "Меню кальяна | The Woo White City — Премиальный Кальян", titleEn: "Shisha Menu | The Woo White City — Premium Shisha", titleTr: "Nargile Menüsü | The Woo White City — Premium Nargile", descAz: "Premium qəlyan təcrübəsi — fərqli tərzlərdə hazırlanan qəlyan çeşidlərimizlə unudulmaz anlar yaşayın.", descRu: "Премиальный кальян — наслаждайтесь незабываемыми моментами с нашими кальянами, приготовленными в разных стилях.", descEn: "Premium shisha experience — enjoy unforgettable moments with our shisha varieties prepared in different styles.", descTr: "Premium nargile deneyimi — farklı stillerde hazırlanan nargile çeşitlerimizle unutulmaz anlar yaşayın.", kwAz: "qəlyan bakı, premium qəlyan, hookah lounge, nargile", kwRu: "кальян баку, премиальный кальян, hookah lounge", kwEn: "shisha baku, premium shisha, hookah lounge", kwTr: "nargile baku, premium nargile, hookah lounge" },
  { id: "snack", titleAz: "Snack Menyu | The Woo White City — Gecə Yeməkləri", titleRu: "Снэк-меню | The Woo White City — Ночные Закуски", titleEn: "Snack Menu | The Woo White City — Late Night Bites", titleTr: "Snack Menü | The Woo White City — Gece Yiyecekleri", descAz: "Snack menyu — saat 23:00-dan sonra aktiv. Həm sürətli, həm də dadlı gecə yeməkləri seçimi.", descRu: "Снэк-меню — доступно после 23:00. Быстрые и вкусные ночные закуски.", descEn: "Snack menu — available after 23:00. Quick and tasty late-night bites.", descTr: "Snack menü — 23:00'ten sonra aktif. Hızlı ve lezzetli gece atıştırmalıkları.", kwAz: "snack menyu, gecə yeməkləri, late night menu, restoran snack", kwRu: "снэк меню, ночные закуски, late night menu", kwEn: "snack menu, late night bites, late night food, restaurant snack", kwTr: "snack menü, gece yiyecekleri, late night menu, restoran snack" },
  { id: "about", titleAz: "Haqqımızda | The Woo White City — Restoran və Lounge", titleRu: "О нас | The Woo White City — Ресторан и Лаунж", titleEn: "About Us | The Woo White City — Restaurant & Lounge", titleTr: "Hakkımızda | The Woo White City — Restoran ve Lounge", descAz: "The Woo White City — Bakının White City hissəsində yerləşən premium restoran və lounge. Ləzzətli yeməklər, canlı musiqi və xüsusi atmosfer.", descRu: "The Woo White City — премиальный ресторан и лаунж в районе White City, Баку. Вкусная еда, живая музыка и особенная атмосфера.", descEn: "The Woo White City — a premium restaurant and lounge in White City, Baku. Delicious food, live music and a special atmosphere.", descTr: "The Woo White City — Bakü'nün White City bölgesinde premium bir restoran ve lounge. Lezzetli yemekler, canlı müzik ve özel atmosfer.", kwAz: "haqqımızda, restoran haqqında, the woo white city, lounge bakı", kwRu: "о нас, о ресторане, the woo white city, лаунж баку", kwEn: "about us, restaurant about, the woo white city, lounge baku", kwTr: "hakkımızda, restoran hakkında, the woo white city, lounge baku" },
  { id: "gallery", titleAz: "Qalereya | The Woo White City — Foto və Video", titleRu: "Галерея | The Woo White City — Фото и Видео", titleEn: "Gallery | The Woo White City — Photos & Videos", titleTr: "Galeri | The Woo White City — Fotoğraf ve Video", descAz: "The Woo White City qalereyası — restoranımızın interyeri, yeməklərimiz, tədbirlərimiz və unudulmaz anların foto və videoları.", descRu: "Галерея The Woo White City — интерьер нашего ресторана, наши блюда, мероприятия и фото и видео незабываемых моментов.", descEn: "The Woo White City gallery — our restaurant interior, our dishes, events and photos and videos of unforgettable moments.", descTr: "The Woo White City galerisi — restoranımızın iç mekanı, yemeklerimiz, etkinlikler ve unutulmaz anların fotoğraf ve videoları.", kwAz: "qalereya bakı, restoran foto, lounge foto, the woo white city qalereya", kwRu: "галерея баку, ресторан фото, лаунж фото", kwEn: "gallery baku, restaurant photos, lounge photos", kwTr: "galeri baku, restoran fotoğrafları, lounge fotoğrafları" },
  { id: "events", titleAz: "Tədbirlər | The Woo White City — Xüsusi Tədbirlər", titleRu: "Мероприятия | The Woo White City — Особые События", titleEn: "Events | The Woo White City — Private Events", titleTr: "Etkinlikler | The Woo White City — Özel Etkinlikler", descAz: "The Woo White City-də xüsusi tədbirlər — ad günü, korporativ tədbirlər, romantik şam yeməyi və daha çoxu.", descRu: "Особые мероприятия в The Woo White City — дни рождения, корпоративные мероприятия, романтический ужин и многое другое.", descEn: "Private events at The Woo White City — birthdays, corporate events, romantic dinners and more.", descTr: "The Woo White City'de özel etkinlikler — doğum günleri, kurumsal etkinlikler, romantik akşam yemekleri ve daha fazlası.", kwAz: "tədbirlər bakı, ad günü restoran, korporativ tədbir, romantik yemək", kwRu: "мероприятия баку, день рождения ресторан, корпоративное мероприятие", kwEn: "events baku, birthday restaurant, corporate event, romantic dinner", kwTr: "etkinlikler baku, doğum günü restoran, kurumsal etkinlik, romantik akşam yemeği" },
  { id: "contact", titleAz: "Əlaqə | The Woo White City — Ünvan və Telefon", titleRu: "Контакты | The Woo White City — Адрес и Телефон", titleEn: "Contact | The Woo White City — Address & Phone", titleTr: "İletişim | The Woo White City — Adres ve Telefon", descAz: "The Woo White City ilə əlaqə — ünvan: 1-ci Yaşıl Ada Küçəsi, White City, Bakı. Telefon: +994 50 213 05 55. Rezervasiya üçün zəng edin.", descRu: "Контакты The Woo White City — адрес: 1-ci Yaşıl Ada Küçəsi, White City, Баку. Телефон: +994 50 213 05 55. Звоните для резервации.", descEn: "Contact The Woo White City — address: 1-ci Yaşıl Ada Küçəsi, White City, Baku. Phone: +994 50 213 05 55. Call for reservations.", descTr: "The Woo White City iletişim — adres: 1-ci Yaşıl Ada Küçəsi, White City, Bakü. Telefon: +994 50 213 05 55. Rezervasyon için arayın.", kwAz: "əlaqə bakı, restoran ünvanı, rezervasiya, the woo white city telefon", kwRu: "контакты баку, адрес ресторана, резервация, the woo white city телефон", kwEn: "contact baku, restaurant address, reservation, the woo white city phone", kwTr: "iletişim baku, restoran adresi, rezervasyon, the woo white city telefon" },
  { id: "reservation", titleAz: "Rezervasiya | The Woo White City — Masa Rezervasiyası", titleRu: "Бронирование | The Woo White City — Резерв Стола", titleEn: "Reservation | The Woo White City — Table Booking", titleTr: "Rezervasyon | The Woo White City — Masa Rezervasyonu", descAz: "The Woo White City-də masa rezervasiyası — WhatsApp üzərən sürətli və asan rezervasiya. White City və Seabreeze Marina filialları.", descRu: "Резерв стола в The Woo White City — быстрое и удобное бронирование через WhatsApp. Филиалы White City и Seabreeze Marina.", descEn: "Table reservation at The Woo White City — quick and easy booking via WhatsApp. White City and Seabreeze Marina branches.", descTr: "The Woo White City'de masa rezervasyonu — WhatsApp üzerinden hızlı ve kolay rezervasyon. White City ve Seabreeze Marina şubeleri.", kwAz: "rezervasiya bakı, masa rezervasiyası, restoran rezervasiya, the woo white city", kwRu: "бронирование баку, резерв стола, резервация ресторан", kwEn: "reservation baku, table booking, restaurant reservation", kwTr: "rezervasyon baku, masa rezervasyonu, restoran rezervasyonu" },
  { id: "qr", titleAz: "QR Menyu | The Woo White City — Online Menyu", titleRu: "QR Меню | The Woo White City — Онлайн Меню", titleEn: "QR Menu | The Woo White City — Online Menu", titleTr: "QR Menü | The Woo White City — Online Menü", descAz: "The Woo White City QR menyu — telefonunuzdan yemək, içki və qəlyan sifariş edin. White City və Seabreeze Marina filialları.", descRu: "QR-меню The Woo White City — заказывайте еду, напитки и кальян с телефона. Филиалы White City и Seabreeze Marina.", descEn: "The Woo White City QR menu — order food, beverages and shisha from your phone. White City and Seabreeze Marina branches.", descTr: "The Woo White City QR menü — telefonunuzdan yemek, içecek ve nargile sipariş edin. White City ve Seabreeze Marina şubeleri.", kwAz: "qr menyu, online menyu, the woo white city menyu", kwRu: "qr меню, онлайн меню, the woo white city меню", kwEn: "qr menu, online menu, the woo white city menu", kwTr: "qr menü, online menü, the woo white city menü" },
  { id: "privacy", titleAz: "Məxfilik Siyasəti | The Woo White City", titleRu: "Политика конфиденциальности | The Woo White City", titleEn: "Privacy Policy | The Woo White City", titleTr: "Gizlilik Politikası | The Woo White City", descAz: "The Woo White City məxfilik siyasəti — şəxsi məlumatlarınızın qorunması, cookie istifadəsi və hüquqlarınız.", descRu: "Политика конфиденциальности The Woo White City — защита ваших персональных данных, использование cookie и ваши права.", descEn: "The Woo White City privacy policy — how we protect your personal data, cookie usage, and your rights.", descTr: "The Woo White City gizlilik politikası — kişisel verilerinizin korunması, çerez kullanımı ve haklarınız.", kwAz: "məxfilik siyasəti, gizlilik, cookie siyasəti, the woo", kwRu: "политика конфиденциальности, приватность, cookie, the woo", kwEn: "privacy policy, data protection, cookie policy, the woo", kwTr: "gizlilik politikası, veri koruma, çerez politikası, the woo" },
  { id: "cookie-policy", titleAz: "Cookie Siyasəti | The Woo White City", titleRu: "Политика использования cookies | The Woo White City", titleEn: "Cookie Policy | The Woo White City", titleTr: "Çerez Politikası | The Woo White City", descAz: "The Woo White City cookie siyasəti — saytda istifadə olunan cookie-lər, kateqoriyalar və razılıq idarəsi.", descRu: "Политика использования cookies The Woo White City — cookies на сайте, категории и управление согласием.", descEn: "The Woo White City cookie policy — cookies used on the site, categories, and consent management.", descTr: "The Woo White City çerez politikası — sitede kullanılan çerezler, kategoriler ve izin yönetimi.", kwAz: "cookie siyasəti, cookie razılığı, the woo", kwRu: "политика cookie, согласие cookie, the woo", kwEn: "cookie policy, cookie consent, the woo", kwTr: "çerez politikası, çerez izni, the woo" },
];

async function main() {
  const db = getDb();

  for (const p of PAGES) {
    const existing = await db.select().from(seoSettings).where(eq(seoSettings.page, p.id));
    if (existing.length > 0) {
      console.log(`Skip ${p.id} — already exists`);
      continue;
    }

    await db.insert(seoSettings).values({
      page: p.id,
      titleAz: p.titleAz,
      titleRu: p.titleRu,
      titleEn: p.titleEn,
      titleTr: p.titleTr,
      descriptionAz: p.descAz,
      descriptionRu: p.descRu,
      descriptionEn: p.descEn,
      descriptionTr: p.descTr,
      keywordsAz: p.kwAz,
      keywordsRu: p.kwRu,
      keywordsEn: p.kwEn,
      keywordsTr: p.kwTr,
      ogTitleAz: p.titleAz,
      ogTitleRu: p.titleRu,
      ogTitleEn: p.titleEn,
      ogTitleTr: p.titleTr,
      ogDescriptionAz: p.descAz,
      ogDescriptionRu: p.descRu,
      ogDescriptionEn: p.descEn,
      ogDescriptionTr: p.descTr,
      ogImage: "https://thewoo.az/assets/og-default.jpg",
    });

    console.log(`Inserted ${p.id}`);
  }

  console.log("\nDone seeding SEO settings.");
  process.exit(0);
}

main().catch((err) => { console.error(err); process.exit(1); });

